CREATE TABLE TEMP_SYS_TRANSACTION
AS
   SELECT *
     FROM SYS_TRANSACTION
    WHERE 1 = 2;

CREATE TABLE TEMP_CUSTOMER
AS
   SELECT *
     FROM CUSTOMER
    WHERE 1 = 2;

CREATE TABLE TEMP_CUSTOMER_BUSINESS
AS
   SELECT *
     FROM CUSTOMER_BUSINESS
    WHERE 1 = 2;

CREATE TABLE TEMP_CUSTOMER_BUSINESS_INFO
AS
   SELECT *
     FROM CUSTOMER_BUSINESS_INFO
    WHERE 1 = 2;

CREATE TABLE TEMP_CUSTOMER_BIZ_BUYER
AS
   SELECT *
     FROM CUSTOMER_BIZ_BUYER
    WHERE 1 = 2;

CREATE TABLE TEMP_CUSTOMER_BIZ_PRODUCT
AS
   SELECT *
     FROM CUSTOMER_BIZ_PRODUCT
    WHERE 1 = 2;

CREATE TABLE TEMP_CUSTOMER_BIZ_COMPETITOR
AS
   SELECT *
     FROM CUSTOMER_BIZ_COMPETITOR
    WHERE 1 = 2;

CREATE TABLE TEMP_CUSTOMER_BIZ_SUPPLIER
AS
   SELECT *
     FROM CUSTOMER_BIZ_SUPPLIER
    WHERE 1 = 2;

CREATE TABLE TEMP_CUSTOMER_RELATION
AS
   SELECT *
     FROM CUSTOMER_RELATION
    WHERE 1 = 2;

CREATE TABLE TEMP_CUSTOMER_BANK_ACCOUNT
AS
   SELECT *
     FROM CUSTOMER_BANK_ACCOUNT
    WHERE 1 = 2;

CREATE TABLE TEMP_CUSTOMER_EXT_BORROWS
AS
   SELECT *
     FROM CUSTOMER_EXT_BORROWS
    WHERE 1 = 2;

CREATE TABLE TEMP_OUTSTANDING_LOANS
AS
   SELECT *
     FROM CUSTOMER_OUTSTANDING_LOANS
    WHERE 1 = 2;

CREATE TABLE TEMP_CUSTOMER_LOAN_COLLATERAL
AS
   SELECT *
     FROM CUSTOMER_LOAN_COLLATERAL
    WHERE 1 = 2;

CREATE TABLE TEMP_CUSTOMER_CREDIT_RATING
AS
   SELECT *
     FROM CUSTOMER_CREDIT_RATING
    WHERE 1 = 2;

CREATE TABLE TEMP_CUSTOMER_DOCUMENT
AS
   SELECT *
     FROM CUSTOMER_DOCUMENT
    WHERE 1 = 2;

CREATE TABLE TEMP_CUSTOMER_GROUP_MEMBER
AS
   SELECT *
     FROM CUSTOMER_GROUP_MEMBER
    WHERE 1 = 2;

CREATE TABLE TEMP_CUSTOMER_CONTACT
AS
   SELECT *
     FROM CUSTOMER_CONTACT
    WHERE 1 = 2;

CREATE TABLE TEMP_CUSTOMER_IDENTITY
AS
   SELECT *
     FROM CUSTOMER_IDENTITY
    WHERE 1 = 2;

CREATE TABLE TEMP_CUSTOMER_BIZ_INDEX
AS
   SELECT *
     FROM CUSTOMER_BIZ_INDEX
    WHERE 1 = 2;

CREATE TABLE TEMP_COLLATERAL
AS
   SELECT *
     FROM COLLATERAL
    WHERE 1 = 2;

CREATE TABLE TEMP_COLLATERAL_PLEDGOR
AS
   SELECT *
     FROM COLLATERAL_PLEDGOR
    WHERE 1 = 2;

CREATE TABLE TEMP_COLLATERAL_PRICING
AS
   SELECT *
     FROM COLLATERAL_PRICING
    WHERE 1 = 2;

CREATE TABLE TEMP_COLLATERAL_DOCUMENT
AS
   SELECT *
     FROM COLLATERAL_DOCUMENT
    WHERE 1 = 2;

CREATE TABLE TEMP_CREDIT_REQUEST
AS
   SELECT *
     FROM CREDIT_APPLICATION_REQUEST
    WHERE 1 = 2;

CREATE TABLE TEMP_CAR_COMMENTS
AS
   SELECT *
     FROM CAR_COMMENTS
    WHERE 1 = 2;

CREATE TABLE TEMP_CAR_RELATIONSHIP
AS
   SELECT *
     FROM CAR_RELATIONSHIP
    WHERE 1 = 2;

CREATE TABLE TEMP_CAR_LIMIT
AS
   SELECT *
     FROM CAR_LIMIT
    WHERE 1 = 2;

CREATE TABLE TEMP_CAR_COLLATERAL
AS
   SELECT *
     FROM CAR_COLLATERAL
    WHERE 1 = 2;

CREATE TABLE TEMP_LIMIT
AS
   SELECT *
     FROM LIMIT
    WHERE 1 = 2;

CREATE TABLE TEMP_FACILITY
AS
   SELECT *
     FROM FACILITY
    WHERE 1 = 2;

CREATE TABLE TEMP_CAR_CUSTOMER_DOCUMENTS
AS
   SELECT *
     FROM CAR_CUSTOMER_DOCUMENTS
    WHERE 1 = 2;

CREATE TABLE TEMP_CAR_COLLATERAL_DOCUMENTS
AS
   SELECT *
     FROM CAR_COLLATERAL_DOCUMENTS
    WHERE 1 = 2;

CREATE TABLE TEMP_CAR_APPLICATION_DOCUMENTS
AS
   SELECT *
     FROM CAR_APPLICATION_DOCUMENTS
    WHERE 1 = 2;

CREATE TABLE TEMP_CAR_CUSTOMER_CONDITIONS
AS
   SELECT *
     FROM CAR_CUSTOMER_CONDITIONS
    WHERE 1 = 2;

CREATE TABLE TEMP_CAR_COLLATERAL_CONDITIONS
AS
   SELECT *
     FROM CAR_COLLATERAL_CONDITIONS
    WHERE 1 = 2;

CREATE TABLE TEMP_APPLICATION_CONDITIONS
AS
   SELECT *
     FROM CAR_APPLICATION_CONDITIONS
    WHERE 1 = 2;