-- This script is used to rebuild fragmented indexes
-- Author: Thang Duong

DECLARE @INDEXNAME AS NVARCHAR(60);
DECLARE @TABLENAME AS NVARCHAR(60);
DECLARE @INDEXFRAG AS FLOAT;
DECLARE @CURIDX AS CURSOR;
DECLARE @cmd AS NVARCHAR(500);  

SET @CURIDX = CURSOR FOR
SELECT OBJECT_NAME(B.OBJECT_ID) AS TABLE_NAME, B.NAME AS INDEX_NAME, AVG_FRAGMENTATION_IN_PERCENT
FROM SYS.DM_DB_INDEX_PHYSICAL_STATS (DB_ID(), NULL, NULL, NULL, NULL) AS A
    JOIN SYS.INDEXES AS B ON A.OBJECT_ID = B.OBJECT_ID AND A.INDEX_ID = B.INDEX_ID
WHERE A.AVG_FRAGMENTATION_IN_PERCENT > 90 AND B.NAME IS NOT NULL
ORDER BY A.AVG_FRAGMENTATION_IN_PERCENT DESC;

OPEN @CURIDX;
FETCH NEXT FROM @CURIDX INTO @TABLENAME, @INDEXNAME, @INDEXFRAG;

WHILE @@FETCH_STATUS = 0
BEGIN
	SET @cmd = 'ALTER INDEX ' + @INDEXNAME + ' ON ' + @TABLENAME + ' REBUILD WITH (FILLFACTOR = 80);';
	EXEC (@cmd);
	--PRINT @TABLENAME + ' ' + @INDEXNAME  + ' ' + CAST(@INDEXFRAG AS VARCHAR(50));
	FETCH NEXT FROM @CURIDX INTO @TABLENAME, @INDEXNAME, @INDEXFRAG;
END;

CLOSE @CURIDX;
DEALLOCATE @CURIDX;