CREATE OR REPLACE PROCEDURE BACKEND_DEV.SP_RO_ByDefaultRuleTest(cus_id in number,sys_tran in number) AS
test CUSTOMER.CUSTOMER_NAME%TYPE;
countnumb NUMBER;
BEGIN
select COUNT(ID) INTO countnumb FROM CUSTOMER_RELATION WHERE CUSTOMER_ID = cus_id;
DBMS_OUTPUT.PUT_LINE(countnumb);
EXCEPTION
WHEN NO_DATA_FOUND THEN DBMS_OUTPUT.PUT_LINE('no data found');
END;
/